export enum GatewayOpCodes {
    Dispatch = 0,
    Heartbeat = 1,
    Identify = 2,
    PresenceUpdate = 3,
    VoiceStateUpdate = 4,
    Resume = 6,
    Reconnect = 7,
    RequestGuildMembers = 8,
    InvalidSession = 9,
    Hello = 10,
    HeartbeatAck = 11,
}

export enum GatewayDispatchEvents {
    Ready = 'READY',
    Resumed = 'RESUMED',
    MessageCreate = 'MESSAGE_CREATE',
    MessageUpdate = 'MESSAGE_UPDATE',
    MessageDelete = 'MESSAGE_DELETE',
    MessageDeleteBulk = 'MESSAGE_DELETE_BULK',
    GuildCreate = 'GUILD_CREATE',
    GuildUpdate = 'GUILD_UPDATE',
    GuildDelete = 'GUILD_DELETE',
    GuildMemberAdd = 'GUILD_MEMBER_ADD',
    GuildMemberUpdate = 'GUILD_MEMBER_UPDATE',
    GuildMemberRemove = 'GUILD_MEMBER_REMOVE',
    ChannelCreate = 'CHANNEL_CREATE',
    ChannelUpdate = 'CHANNEL_UPDATE',
    ChannelDelete = 'CHANNEL_DELETE',
    TypingStart = 'TYPING_START',
    PresenceUpdate = 'PRESENCE_UPDATE',
    VoiceStateUpdate = 'VOICE_STATE_UPDATE',
    VoiceServerUpdate = 'VOICE_SERVER_UPDATE',
    MessageReactionAdd = 'MESSAGE_REACTION_ADD',
    MessageReactionRemove = 'MESSAGE_REACTION_REMOVE',
}

export enum GatewayCloseCodes {
    UnknownError = 4000,
    UnknownOpCode = 4001,
    DecodeError = 4002,
    NotAuthenticated = 4003,
    AuthenticationFailed = 4004,
    AlreadyAuthenticated = 4005,
    InvalidSeq = 4007,
    RateLimited = 4008,
    SessionTimedOut = 4009,
    InvalidShard = 4010,
    ShardingRequired = 4011,
    InvalidAPIVersion = 4012,
    InvalidIntents = 4013,
    DisallowedIntents = 4014,
}
